- name: Update apt cache if needed
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: add ppas
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: ppas
  when: ppas is defined
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: pkgs
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: pip_pkgs
  when: pip_pkgs is defined
- name: Install npm pkgs
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: npm_pkgs
