---
# tasks file for common
- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
- name: install packages
  apt: name={{ item }} state=present
  with_items: pkgs
# - name: Install nodejs packages
#   npm: name={{ item }} global=yes state=present
#   with_items: npm_pkgs
