# Include variables and define needed variables.
# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
