# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'

# tasks file for common
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: pip_pkgs
