- name: Update apt cache if needed
    yum:
      update_cachei: yes
      cache_valid_time: 3600
- name: Ensure Apache is installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: pkgs
