- name: Install list of packages
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: pkgs
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: pip_pkgs
  when: pip_pkgs is defined
